### ISSUE TITLE
Problema al pedir repositorios privados en github

### ISSUE THREAD

**Issue by Dangaran** [Rstats-courses/cursoR-AEET2016#2]
Buenas,

estaba intentando pedir los repositorios privados de Github desde la página que nos dijisteis (https://education.github.com/) y al pulsar "Request_a_discount" y elegir "estudiante" (o investigador, probé ambas) y "cuenta de organización". No me reconoce la cuenta del CSIC.

La cuenta de github la tengo creada con un gmail pero en el perfil tengo añadidos el mail del CSIC e incluso el de la universidad. Y aún poniendo como correo primario cualquiera de ellos no me deja.

Sabéis como hacerlo?? O es que me he dejado algún paso??

Dani

**Comment by Pakillo** [comment]
Hola Dani! 

Guay que sigas animado a usar github :)

El correo del CSIC deberia valer. Tienes que añadir tu correo del CSIC a tu perfil (en https://github.com/settings/emails) y una vez verificado ya te deja

Sospecho que el problema puede estar en lo 'cuenta de organizacion'. Debes pedir un descuento *individual*, no de organización (aunque pongas tu email del CSIC)

Prueba a ver...

Suerte!

**Comment by Dangaran** [comment]
ok, probaré ahora porque lo tengo verificado y no me lo acepta así que el problema debe ser en lo de "cuenta de organización", con lo que me contesten os digo

**Comment by Dangaran** [comment]
Con la cuenta del CSIC no me han dejado. Me han contestado esto:
"Unfortunately, we weren't able to approve your educational discount request. The most common reason is that we weren't able to verify your academic status."

Voy a probar con la de la universidad, pero si no reconocen al CSIC como entidad para hacer el descuento...poca gente lo usará!! Lo que no se es si no me reconocen como CSIC por ser estudiante predoctoral y a no ser que estés como categoría de investigador no apareces o porque directamente no reconocen la institución como tal

**Comment by Pakillo** [comment]
Strange... Más que la categoría de investigador, debe de ser que no reconocen al CSIC como institución académica. Puedes escribirle diciendo que el CSIC es el National Research Council y que por favor lo incluyan... Tal vez @ibartomeus tenga más info (creo que él usó su cuenta del CSIC)

**Comment by ibartomeus** [comment]
Dicen: "If you do not have a school-issued email address, or your application using a school-issued email address is denied, you may reapply using the "I do not have a school-issued email" drop-down option to attach supplementary photo proof of enrollment. Make sure your proof is official and is dated to show that you are currently enrolled." 

Yo creo que si se lo explicas bien y eres amable, su politica es de concederlo en caso de duda.

**Comment by Dangaran** [comment]
Al final al intentarlo con el mail de la universidad si que me ha dejado, si alguno lo intenta con el CSIC que lo ponga por aquí!!
